version: "3.9"
services:
  plex-api:
    hostname: "plex-api"
    container_name: "plex-api"
    image: "ghcr.io/cyb3rgh05t/plex-api:latest"
    environment:
      - "TZ=Europe/Berlin"
      - "NODE_ENV=production"
    restart: "unless-stopped"
    ports:
      - "3005:3005"
    volumes:
      - plex-api-config:/app/config

volumes:
  plex-api-config:
    name: plex-api-config

networks:
  proxy:
    external: true
