---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  plex-api:
    hostname: "plex-api"
    container_name: "plex-api"
    environment:
      - "TZ=Europe/Berlin"
      - "VITE_PLEX_SERVER_URL=https://your-plex-server:32400"
      - "VITE_PLEX_TOKEN=YOUR-PLEX-TOKEN"
    image: "ghcr.io/cyb3rgh05t/plex-api:latest"
    restart: "unless-stopped"
    ports:
      - "3005:3005"
