version: "3.9"
services:
  plex-api:
    hostname: "plex-api"
    container_name: "plex-api"
    environment:
      - "TZ=${TZ}"
      - "NODE_ENV=production"
      - "PORT=3005"
      - "ALLOWED_HOSTS=*"
    image: "ghcr.io/cyb3rgh05t/plex-api:dev"
    restart: "unless-stopped"
    ports:
      - "3005:3005" # frontend
      - "3006:3006" # proxy-server backend
    volumes:
      - "/opt/appdata/plex-api:/app/data"
